/**
 * enemy.ts — enemy data definitions for the damage simulator.
 *
 * Enemy stats come from `NpcParam` and `CalcCorrectGraph` for enemy bodies.
 * For the in-game "red glowing" enemies the ` defence / absorption` fields map
 * to the in-game damage negation tab. Bosses additionally expose NG cycle
 * multipliers.
 */

import { AttackPowerType } from "../types";
import type { AbsorptionKey } from "./defense";

export interface Enemy {
  id: string;
  name: string;
  /** Per-damage-type flat defence (the attack-ratio input). */
  defence: Partial<Record<AttackPowerType, number>>;
  /** Absorption percentages for each label shown in the UI. */
  absorption: Partial<Record<AttackPowerType, number>>;
  /** Status effect resistances: threshold to proc. */
  statusResistances?: Partial<Record<AttackPowerType, number>>;
  /** Enemy HP at NG base. */
  hp?: number;
  /** Boss multiplier by NG cycle (0=NG,0.5=NG+1,...). */
  ngHpMultiplier?: Record<number, number>;
  /** Tags: "Void" | "LivingInDeath" | "AncientDraconic" | "Draconic". */
  enemyTypes?: string[];
}

export const enemyDatabase: Enemy[] = [
  {
    id: "malenia",
    name: "Malenia, Blade of Miquella",
    defence: {
      [AttackPowerType.PHYSICAL]: 1200,
      [AttackPowerType.MAGIC]: 865,
      [AttackPowerType.FIRE]: 807,
      [AttackPowerType.LIGHTNING]: 765,
      [AttackPowerType.HOLY]: 1087,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 20,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 25,
      [AttackPowerType.LIGHTNING]: 25,
      [AttackPowerType.HOLY]: 40,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 720,
      [AttackPowerType.FROST]: 300,
      [AttackPowerType.POISON]: 1000,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 33251,
    enemyTypes: ["Void"],
  },
  {
    id: "godfrey-hoarah-lou",
    name: "Godfrey, First Elden Lord",
    defence: {
      [AttackPowerType.PHYSICAL]: 1200,
      [AttackPowerType.MAGIC]: 1087,
      [AttackPowerType.FIRE]: 865,
      [AttackPowerType.LIGHTNING]: 765,
      [AttackPowerType.HOLY]: 807,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 10,
      [AttackPowerType.MAGIC]: 30,
      [AttackPowerType.FIRE]: 30,
      [AttackPowerType.LIGHTNING]: 30,
      [AttackPowerType.HOLY]: 30,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 600,
      [AttackPowerType.FROST]: 600,
      [AttackPowerType.POISON]: 1000,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 37395,
  },
  {
    id: "mohg-lord-of-blood",
    name: "Mohg, Lord of Blood",
    defence: {
      [AttackPowerType.PHYSICAL]: 1181,
      [AttackPowerType.MAGIC]: 1082,
      [AttackPowerType.FIRE]: 807,
      [AttackPowerType.LIGHTNING]: 765,
      [AttackPowerType.HOLY]: 1087,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 30,
      [AttackPowerType.MAGIC]: 30,
      [AttackPowerType.FIRE]: 20,
      [AttackPowerType.LIGHTNING]: 20,
      [AttackPowerType.HOLY]: 0,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 9999,
      [AttackPowerType.FROST]: 600,
      [AttackPowerType.POISON]: 1000,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 41824,
  },
  {
    id: "fire-giant",
    name: "Fire Giant",
    defence: {
      [AttackPowerType.PHYSICAL]: 1200,
      [AttackPowerType.MAGIC]: 924,
      [AttackPowerType.FIRE]: 1087,
      [AttackPowerType.LIGHTNING]: 765,
      [AttackPowerType.HOLY]: 1087,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 20,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 80,
      [AttackPowerType.LIGHTNING]: 30,
      [AttackPowerType.HOLY]: 30,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 600,
      [AttackPowerType.FROST]: 600,
      [AttackPowerType.POISON]: 1000,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 41804,
    enemyTypes: ["AncientDraconic"],
  },

  // ─── Final boss duo (Radagon + Elden Beast) ───────────────────────────────
  {
    id: "radagon",
    name: "Radagon of the Golden Order",
    defence: {
      [AttackPowerType.PHYSICAL]: 1200,
      [AttackPowerType.MAGIC]: 1087,
      [AttackPowerType.FIRE]: 865,
      [AttackPowerType.LIGHTNING]: 765,
      [AttackPowerType.HOLY]: 807,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 20,
      [AttackPowerType.MAGIC]: 30,
      [AttackPowerType.FIRE]: 30,
      [AttackPowerType.LIGHTNING]: 30,
      [AttackPowerType.HOLY]: 40,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 600,
      [AttackPowerType.FROST]: 600,
      [AttackPowerType.POISON]: 1000,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 26000,
    enemyTypes: ["Void", "Demigod"],
  },
  {
    id: "elden-beast",
    name: "Elden Beast",
    defence: {
      [AttackPowerType.PHYSICAL]: 1200,
      [AttackPowerType.MAGIC]: 1087,
      [AttackPowerType.FIRE]: 865,
      [AttackPowerType.LIGHTNING]: 765,
      [AttackPowerType.HOLY]: 807,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 20,
      [AttackPowerType.MAGIC]: 30,
      [AttackPowerType.FIRE]: 30,
      [AttackPowerType.LIGHTNING]: 30,
      [AttackPowerType.HOLY]: 40,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 9999,
      [AttackPowerType.FROST]: 600,
      [AttackPowerType.POISON]: 2000,
      [AttackPowerType.SCARLET_ROT]: 2000,
    },
    hp: 28000,
    enemyTypes: ["Void", "OuterGod"],
  },

  // ─── Shadow of the Erdtree DLC bosses ────────────────────────────────────
  {
    id: "bayle-the-dread",
    name: "Bayle the Dread",
    defence: {
      [AttackPowerType.PHYSICAL]: 1273,
      [AttackPowerType.MAGIC]: 1088,
      [AttackPowerType.FIRE]: 1168,
      [AttackPowerType.LIGHTNING]: 904,
      [AttackPowerType.HOLY]: 1088,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 20,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 40,
      [AttackPowerType.LIGHTNING]: 10,
      [AttackPowerType.HOLY]: 20,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 760,
      [AttackPowerType.FROST]: 570,
      [AttackPowerType.POISON]: 1000,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 60000,
    enemyTypes: ["Draconic"],
  },
  {
    id: "messmer-the-impaler",
    name: "Messmer the Impaler",
    defence: {
      [AttackPowerType.PHYSICAL]: 1200,
      [AttackPowerType.MAGIC]: 920,
      [AttackPowerType.FIRE]: 1087,
      [AttackPowerType.LIGHTNING]: 765,
      [AttackPowerType.HOLY]: 865,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 10,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 40,
      [AttackPowerType.LIGHTNING]: 30,
      [AttackPowerType.HOLY]: 20,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 700,
      [AttackPowerType.FROST]: 480,
      [AttackPowerType.POISON]: 1000,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 42500,
    enemyTypes: ["Demigod"],
  },
  {
    id: "consort-radahn",
    name: "Promised Consort Radahn",
    defence: {
      [AttackPowerType.PHYSICAL]: 1366,
      [AttackPowerType.MAGIC]: 1087,
      [AttackPowerType.FIRE]: 1004,
      [AttackPowerType.LIGHTNING]: 865,
      [AttackPowerType.HOLY]: 1004,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 20,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 20,
      [AttackPowerType.LIGHTNING]: 20,
      [AttackPowerType.HOLY]: 30,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 900,
      [AttackPowerType.FROST]: 600,
      [AttackPowerType.POISON]: 2000,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 58000,
    enemyTypes: ["Demigod", "Void"],
  },

  // ─── Base game major bosses ──────────────────────────────────────────────
  {
    id: "radahn-festival",
    name: "Radahn, Scourge of the Stars",
    defence: {
      [AttackPowerType.PHYSICAL]: 1200,
      [AttackPowerType.MAGIC]: 1087,
      [AttackPowerType.FIRE]: 807,
      [AttackPowerType.LIGHTNING]: 865,
      [AttackPowerType.HOLY]: 924,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 20,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 40,
      [AttackPowerType.LIGHTNING]: 10,
      [AttackPowerType.HOLY]: 20,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 600,
      [AttackPowerType.FROST]: 600,
      [AttackPowerType.POISON]: 1000,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 36000,
    enemyTypes: ["Demigod"],
  },
  {
    id: "placidusax",
    name: "Dragonlord Placidusax",
    defence: {
      [AttackPowerType.PHYSICAL]: 1273,
      [AttackPowerType.MAGIC]: 1168,
      [AttackPowerType.FIRE]: 1273,
      [AttackPowerType.LIGHTNING]: 1004,
      [AttackPowerType.HOLY]: 1088,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 20,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 40,
      [AttackPowerType.LIGHTNING]: 10,
      [AttackPowerType.HOLY]: 20,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 760,
      [AttackPowerType.FROST]: 600,
      [AttackPowerType.POISON]: 1000,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 42000,
    enemyTypes: ["AncientDraconic"],
  },
  {
    id: "morgott",
    name: "Morgott, the Omen King",
    defence: {
      [AttackPowerType.PHYSICAL]: 1200,
      [AttackPowerType.MAGIC]: 1004,
      [AttackPowerType.FIRE]: 865,
      [AttackPowerType.LIGHTNING]: 765,
      [AttackPowerType.HOLY]: 924,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 10,
      [AttackPowerType.MAGIC]: 30,
      [AttackPowerType.FIRE]: 30,
      [AttackPowerType.LIGHTNING]: 30,
      [AttackPowerType.HOLY]: 30,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 1000,
      [AttackPowerType.FROST]: 600,
      [AttackPowerType.POISON]: 1000,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 12100,
    enemyTypes: ["Demigod"],
  },
  {
    id: "margit",
    name: "Margit, the Fell Omen",
    defence: {
      [AttackPowerType.PHYSICAL]: 1100,
      [AttackPowerType.MAGIC]: 924,
      [AttackPowerType.FIRE]: 807,
      [AttackPowerType.LIGHTNING]: 765,
      [AttackPowerType.HOLY]: 865,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 10,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 30,
      [AttackPowerType.LIGHTNING]: 30,
      [AttackPowerType.HOLY]: 30,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 540,
      [AttackPowerType.FROST]: 480,
      [AttackPowerType.POISON]: 900,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 4100,
    enemyTypes: ["Demigod"],
  },
  {
    id: "godskin-duo",
    name: "Godskin Duo",
    defence: {
      [AttackPowerType.PHYSICAL]: 1130,
      [AttackPowerType.MAGIC]: 924,
      [AttackPowerType.FIRE]: 865,
      [AttackPowerType.LIGHTNING]: 865,
      [AttackPowerType.HOLY]: 865,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 20,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 40,
      [AttackPowerType.LIGHTNING]: 20,
      [AttackPowerType.HOLY]: 20,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 420,
      [AttackPowerType.FROST]: 300,
      [AttackPowerType.POISON]: 900,
      [AttackPowerType.SCARLET_ROT]: 1200,
    },
    hp: 22771,
    enemyTypes: ["Demigod"],
  },
  {
    id: "astel-naturalborn",
    name: "Astel, Naturalborn of the Void",
    defence: {
      [AttackPowerType.PHYSICAL]: 1170,
      [AttackPowerType.MAGIC]: 1087,
      [AttackPowerType.FIRE]: 924,
      [AttackPowerType.LIGHTNING]: 865,
      [AttackPowerType.HOLY]: 1087,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 20,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 20,
      [AttackPowerType.LIGHTNING]: 20,
      [AttackPowerType.HOLY]: 30,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 600,
      [AttackPowerType.FROST]: 600,
      [AttackPowerType.POISON]: 1000,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 19800,
    enemyTypes: ["Void", "Alien"],
  },
  {
    id: "loretta-haligtree",
    name: "Loretta, Knight of the Haligtree",
    defence: {
      [AttackPowerType.PHYSICAL]: 1100,
      [AttackPowerType.MAGIC]: 1087,
      [AttackPowerType.FIRE]: 807,
      [AttackPowerType.LIGHTNING]: 765,
      [AttackPowerType.HOLY]: 924,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 10,
      [AttackPowerType.MAGIC]: 30,
      [AttackPowerType.FIRE]: 20,
      [AttackPowerType.LIGHTNING]: 30,
      [AttackPowerType.HOLY]: 30,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 600,
      [AttackPowerType.FROST]: 600,
      [AttackPowerType.POISON]: 1000,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 12100,
    enemyTypes: ["Knight"],
  },
  {
    id: "crucible-knight",
    name: "Crucible Knight",
    defence: {
      [AttackPowerType.PHYSICAL]: 1100,
      [AttackPowerType.MAGIC]: 865,
      [AttackPowerType.FIRE]: 807,
      [AttackPowerType.LIGHTNING]: 765,
      [AttackPowerType.HOLY]: 865,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 30,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 20,
      [AttackPowerType.LIGHTNING]: 20,
      [AttackPowerType.HOLY]: 20,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 300,
      [AttackPowerType.FROST]: 300,
      [AttackPowerType.POISON]: 900,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 4500,
    enemyTypes: ["Knight"],
  },
  {
    id: "tree-sentinel",
    name: "Tree Sentinel",
    defence: {
      [AttackPowerType.PHYSICAL]: 1100,
      [AttackPowerType.MAGIC]: 865,
      [AttackPowerType.FIRE]: 807,
      [AttackPowerType.LIGHTNING]: 807,
      [AttackPowerType.HOLY]: 807,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 20,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 20,
      [AttackPowerType.LIGHTNING]: 0,
      [AttackPowerType.HOLY]: 20,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 480,
      [AttackPowerType.FROST]: 600,
      [AttackPowerType.POISON]: 1000,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 4700,
    enemyTypes: ["Knight"],
  },
  {
    id: "rennala",
    name: "Rennala, Queen of the Full Moon",
    defence: {
      [AttackPowerType.PHYSICAL]: 1000,
      [AttackPowerType.MAGIC]: 1200,
      [AttackPowerType.FIRE]: 807,
      [AttackPowerType.LIGHTNING]: 765,
      [AttackPowerType.HOLY]: 865,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 10,
      [AttackPowerType.MAGIC]: 30,
      [AttackPowerType.FIRE]: 30,
      [AttackPowerType.LIGHTNING]: 30,
      [AttackPowerType.HOLY]: 30,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 300,
      [AttackPowerType.FROST]: 300,
      [AttackPowerType.POISON]: 900,
      [AttackPowerType.SCARLET_ROT]: 1200,
    },
    hp: 8400,
    enemyTypes: ["Demigod"],
  },

  // ─── Additional enemies (v1.0.4) ─────────────────────────────────────────
  {
    id: "bell-bearing-hunter",
    name: "Bell Bearing Hunter",
    defence: {
      [AttackPowerType.PHYSICAL]: 1100,
      [AttackPowerType.MAGIC]: 924,
      [AttackPowerType.FIRE]: 865,
      [AttackPowerType.LIGHTNING]: 765,
      [AttackPowerType.HOLY]: 865,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 20,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 20,
      [AttackPowerType.LIGHTNING]: 10,
      [AttackPowerType.HOLY]: 20,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 300,
      [AttackPowerType.FROST]: 300,
      [AttackPowerType.POISON]: 900,
      [AttackPowerType.SCARLET_ROT]: 1200,
    },
    hp: 5500,
  },
  {
    id: "night-cavalry",
    name: "Night's Cavalry",
    defence: {
      [AttackPowerType.PHYSICAL]: 1100,
      [AttackPowerType.MAGIC]: 865,
      [AttackPowerType.FIRE]: 807,
      [AttackPowerType.LIGHTNING]: 807,
      [AttackPowerType.HOLY]: 807,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 20,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 20,
      [AttackPowerType.LIGHTNING]: 0,
      [AttackPowerType.HOLY]: 20,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 480,
      [AttackPowerType.FROST]: 600,
      [AttackPowerType.POISON]: 1000,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 4900,
  },
  {
    id: "fallingstar-beast",
    name: "Fallingstar Beast",
    defence: {
      [AttackPowerType.PHYSICAL]: 1200,
      [AttackPowerType.MAGIC]: 865,
      [AttackPowerType.FIRE]: 1181,
      [AttackPowerType.LIGHTNING]: 765,
      [AttackPowerType.HOLY]: 1087,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 20,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 40,
      [AttackPowerType.LIGHTNING]: 10,
      [AttackPowerType.HOLY]: 20,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 600,
      [AttackPowerType.FROST]: 600,
      [AttackPowerType.POISON]: 1000,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 12700,
    enemyTypes: ["Alien"],
  },
  {
    id: "magma-wyrm",
    name: "Magma Wyrm",
    defence: {
      [AttackPowerType.PHYSICAL]: 1181,
      [AttackPowerType.MAGIC]: 865,
      [AttackPowerType.FIRE]: 1273,
      [AttackPowerType.LIGHTNING]: 765,
      [AttackPowerType.HOLY]: 924,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 20,
      [AttackPowerType.MAGIC]: 30,
      [AttackPowerType.FIRE]: 80,
      [AttackPowerType.LIGHTNING]: 20,
      [AttackPowerType.HOLY]: 30,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 600,
      [AttackPowerType.FROST]: 600,
      [AttackPowerType.POISON]: 1000,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 14700,
    enemyTypes: ["Draconic"],
  },
  {
    id: "leonine-misbegotten",
    name: "Leonine Misbegotten",
    defence: {
      [AttackPowerType.PHYSICAL]: 1100,
      [AttackPowerType.MAGIC]: 865,
      [AttackPowerType.FIRE]: 807,
      [AttackPowerType.LIGHTNING]: 765,
      [AttackPowerType.HOLY]: 865,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 10,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 20,
      [AttackPowerType.LIGHTNING]: 20,
      [AttackPowerType.HOLY]: 20,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 480,
      [AttackPowerType.FROST]: 480,
      [AttackPowerType.POISON]: 900,
      [AttackPowerType.SCARLET_ROT]: 1200,
    },
    hp: 5100,
  },
  {
    id: "crucible-knight-ordovis",
    name: "Crucible Knight (Ordovis)",
    defence: {
      [AttackPowerType.PHYSICAL]: 1100,
      [AttackPowerType.MAGIC]: 865,
      [AttackPowerType.FIRE]: 807,
      [AttackPowerType.LIGHTNING]: 765,
      [AttackPowerType.HOLY]: 865,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 30,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 20,
      [AttackPowerType.LIGHTNING]: 20,
      [AttackPowerType.HOLY]: 20,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 300,
      [AttackPowerType.FROST]: 300,
      [AttackPowerType.POISON]: 900,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 6000,
    enemyTypes: ["Knight"],
  },
  {
    id: "dragonkin-soldier",
    name: "Dragonkin Soldier",
    defence: {
      [AttackPowerType.PHYSICAL]: 1200,
      [AttackPowerType.MAGIC]: 924,
      [AttackPowerType.FIRE]: 924,
      [AttackPowerType.LIGHTNING]: 1087,
      [AttackPowerType.HOLY]: 924,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 20,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 20,
      [AttackPowerType.LIGHTNING]: 40,
      [AttackPowerType.HOLY]: 20,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 600,
      [AttackPowerType.FROST]: 600,
      [AttackPowerType.POISON]: 1000,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 14500,
    enemyTypes: ["Draconic"],
  },
  {
    id: "ancestral-spirit",
    name: "Ancestor Spirit",
    defence: {
      [AttackPowerType.PHYSICAL]: 1100,
      [AttackPowerType.MAGIC]: 924,
      [AttackPowerType.FIRE]: 865,
      [AttackPowerType.LIGHTNING]: 865,
      [AttackPowerType.HOLY]: 924,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 10,
      [AttackPowerType.MAGIC]: 30,
      [AttackPowerType.FIRE]: 30,
      [AttackPowerType.LIGHTNING]: 30,
      [AttackPowerType.HOLY]: 30,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 600,
      [AttackPowerType.FROST]: 600,
      [AttackPowerType.POISON]: 1000,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 9800,
  },
  {
    id: "regal-ancestor-spirit",
    name: "Regal Ancestor Spirit",
    defence: {
      [AttackPowerType.PHYSICAL]: 1200,
      [AttackPowerType.MAGIC]: 1004,
      [AttackPowerType.FIRE]: 924,
      [AttackPowerType.LIGHTNING]: 924,
      [AttackPowerType.HOLY]: 1004,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 20,
      [AttackPowerType.MAGIC]: 30,
      [AttackPowerType.FIRE]: 30,
      [AttackPowerType.LIGHTNING]: 30,
      [AttackPowerType.HOLY]: 30,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 600,
      [AttackPowerType.FROST]: 600,
      [AttackPowerType.POISON]: 1200,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 16000,
  },
  {
    id: "valiant-gargoyle",
    name: "Valiant Gargoyle",
    defence: {
      [AttackPowerType.PHYSICAL]: 1130,
      [AttackPowerType.MAGIC]: 865,
      [AttackPowerType.FIRE]: 807,
      [AttackPowerType.LIGHTNING]: 765,
      [AttackPowerType.HOLY]: 1004,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 20,
      [AttackPowerType.MAGIC]: 30,
      [AttackPowerType.FIRE]: 30,
      [AttackPowerType.LIGHTNING]: 20,
      [AttackPowerType.HOLY]: 40,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 600,
      [AttackPowerType.FROST]: 480,
      [AttackPowerType.POISON]: 1000,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 8600,
  },
  {
    id: "black-knife-assassin",
    name: "Black Knife Assassin",
    defence: {
      [AttackPowerType.PHYSICAL]: 1000,
      [AttackPowerType.MAGIC]: 865,
      [AttackPowerType.FIRE]: 807,
      [AttackPowerType.LIGHTNING]: 765,
      [AttackPowerType.HOLY]: 924,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 10,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 20,
      [AttackPowerType.LIGHTNING]: 20,
      [AttackPowerType.HOLY]: 20,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 420,
      [AttackPowerType.FROST]: 360,
      [AttackPowerType.POISON]: 900,
      [AttackPowerType.SCARLET_ROT]: 1200,
    },
    hp: 3300,
    enemyTypes: ["Knight"],
  },
  {
    id: "eleshar-blue-maned",
    name: "Eleonora, Violet Frost",
    defence: {
      [AttackPowerType.PHYSICAL]: 1100,
      [AttackPowerType.MAGIC]: 865,
      [AttackPowerType.FIRE]: 865,
      [AttackPowerType.LIGHTNING]: 765,
      [AttackPowerType.HOLY]: 924,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 20,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 20,
      [AttackPowerType.LIGHTNING]: 20,
      [AttackPowerType.HOLY]: 20,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 480,
      [AttackPowerType.FROST]: 480,
      [AttackPowerType.POISON]: 900,
      [AttackPowerType.SCARLET_ROT]: 1200,
    },
    hp: 6200,
  },
  {
    id: "sanguine-noble",
    name: "Sanguine Noble",
    defence: {
      [AttackPowerType.PHYSICAL]: 1000,
      [AttackPowerType.MAGIC]: 865,
      [AttackPowerType.FIRE]: 807,
      [AttackPowerType.LIGHTNING]: 765,
      [AttackPowerType.HOLY]: 924,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 10,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 20,
      [AttackPowerType.LIGHTNING]: 20,
      [AttackPowerType.HOLY]: 20,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 780,
      [AttackPowerType.FROST]: 300,
      [AttackPowerType.POISON]: 900,
      [AttackPowerType.SCARLET_ROT]: 1200,
    },
    hp: 4500,
  },
  {
    id: "necalli-boreal-owl",
    name: "Necalli (Boreal Owl)",
    defence: {
      [AttackPowerType.PHYSICAL]: 1100,
      [AttackPowerType.MAGIC]: 924,
      [AttackPowerType.FIRE]: 865,
      [AttackPowerType.LIGHTNING]: 865,
      [AttackPowerType.HOLY]: 924,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 20,
      [AttackPowerType.MAGIC]: 30,
      [AttackPowerType.FIRE]: 30,
      [AttackPowerType.LIGHTNING]: 30,
      [AttackPowerType.HOLY]: 30,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 480,
      [AttackPowerType.FROST]: 780,
      [AttackPowerType.POISON]: 1200,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 6700,
  },
  {
    id: "black-knife-tiche",
    name: "Black Knife Tiche",
    defence: {
      [AttackPowerType.PHYSICAL]: 1000,
      [AttackPowerType.MAGIC]: 924,
      [AttackPowerType.FIRE]: 865,
      [AttackPowerType.LIGHTNING]: 765,
      [AttackPowerType.HOLY]: 1087,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 10,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 20,
      [AttackPowerType.LIGHTNING]: 20,
      [AttackPowerType.HOLY]: 40,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 600,
      [AttackPowerType.FROST]: 480,
      [AttackPowerType.POISON]: 900,
      [AttackPowerType.SCARLET_ROT]: 1200,
    },
    hp: 4800,
    enemyTypes: ["Knight"],
  },
  {
    id: "cleanrot-knight",
    name: "Cleanrot Knight",
    defence: {
      [AttackPowerType.PHYSICAL]: 1100,
      [AttackPowerType.MAGIC]: 865,
      [AttackPowerType.FIRE]: 865,
      [AttackPowerType.LIGHTNING]: 765,
      [AttackPowerType.HOLY]: 924,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 20,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 20,
      [AttackPowerType.LIGHTNING]: 10,
      [AttackPowerType.HOLY]: 30,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 480,
      [AttackPowerType.FROST]: 480,
      [AttackPowerType.POISON]: 900,
      [AttackPowerType.SCARLET_ROT]: 1200,
    },
    hp: 3700,
    enemyTypes: ["Knight"],
  },
  {
    id: "puddle-pirate",
    name: "Dung Puppet (Pirate)",
    defence: {
      [AttackPowerType.PHYSICAL]: 1000,
      [AttackPowerType.MAGIC]: 865,
      [AttackPowerType.FIRE]: 807,
      [AttackPowerType.LIGHTNING]: 807,
      [AttackPowerType.HOLY]: 865,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 10,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 20,
      [AttackPowerType.LIGHTNING]: 20,
      [AttackPowerType.HOLY]: 20,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 420,
      [AttackPowerType.FROST]: 360,
      [AttackPowerType.POISON]: 780,
      [AttackPowerType.SCARLET_ROT]: 1200,
    },
    hp: 4200,
    enemyTypes: ["Living Force"],
  },
  {
    id: "iron-dancer-dungeater",
    name: "Iron Chevalier",
    defence: {
      [AttackPowerType.PHYSICAL]: 1100,
      [AttackPowerType.MAGIC]: 924,
      [AttackPowerType.FIRE]: 865,
      [AttackPowerType.LIGHTNING]: 765,
      [AttackPowerType.HOLY]: 924,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 20,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 20,
      [AttackPowerType.LIGHTNING]: 20,
      [AttackPowerType.HOLY]: 20,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 600,
      [AttackPowerType.FROST]: 480,
      [AttackPowerType.POISON]: 900,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 5500,
  },
  {
    id: "mausoleum-knight",
    name: "Cemetery Shade",
    defence: {
      [AttackPowerType.PHYSICAL]: 1000,
      [AttackPowerType.MAGIC]: 924,
      [AttackPowerType.FIRE]: 865,
      [AttackPowerType.LIGHTNING]: 765,
      [AttackPowerType.HOLY]: 1004,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 10,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 30,
      [AttackPowerType.LIGHTNING]: 20,
      [AttackPowerType.HOLY]: 30,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 300,
      [AttackPowerType.FROST]: 480,
      [AttackPowerType.POISON]: 780,
      [AttackPowerType.SCARLET_ROT]: 1200,
    },
    hp: 3000,
  },
  {
    id: "black-knife-tiche-boss",
    name: "Black Knife Tiche",
    defence: {
      [AttackPowerType.PHYSICAL]: 800,
      [AttackPowerType.MAGIC]: 700,
      [AttackPowerType.FIRE]: 700,
      [AttackPowerType.LIGHTNING]: 700,
      [AttackPowerType.HOLY]: 900,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 10,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 20,
      [AttackPowerType.LIGHTNING]: 20,
      [AttackPowerType.HOLY]: 40,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 600,
      [AttackPowerType.FROST]: 360,
      [AttackPowerType.POISON]: 1000,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 15000,
    enemyTypes: ["Void"],
  },
  {
    id: "mimic-tear",
    name: "Mimic Tear",
    defence: {
      [AttackPowerType.PHYSICAL]: 750,
      [AttackPowerType.MAGIC]: 750,
      [AttackPowerType.FIRE]: 750,
      [AttackPowerType.LIGHTNING]: 750,
      [AttackPowerType.HOLY]: 750,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 20,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 20,
      [AttackPowerType.LIGHTNING]: 20,
      [AttackPowerType.HOLY]: 20,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 600,
      [AttackPowerType.FROST]: 480,
      [AttackPowerType.POISON]: 1000,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 12000,
    enemyTypes: ["Void"],
  },
  {
    id: "lhutel-the-headless",
    name: "Lhutel the Headless",
    defence: {
      [AttackPowerType.PHYSICAL]: 800,
      [AttackPowerType.MAGIC]: 850,
      [AttackPowerType.FIRE]: 765,
      [AttackPowerType.LIGHTNING]: 850,
      [AttackPowerType.HOLY]: 900,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 20,
      [AttackPowerType.MAGIC]: 30,
      [AttackPowerType.FIRE]: 20,
      [AttackPowerType.LIGHTNING]: 30,
      [AttackPowerType.HOLY]: 40,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 9999,
      [AttackPowerType.FROST]: 360,
      [AttackPowerType.POISON]: 1000,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 10000,
    enemyTypes: ["Void"],
  },
  {
    id: "cleanrot-knight-finlay",
    name: "Cleanrot Knight Finlay",
    defence: {
      [AttackPowerType.PHYSICAL]: 850,
      [AttackPowerType.MAGIC]: 765,
      [AttackPowerType.FIRE]: 807,
      [AttackPowerType.LIGHTNING]: 765,
      [AttackPowerType.HOLY]: 865,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 20,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 30,
      [AttackPowerType.LIGHTNING]: 20,
      [AttackPowerType.HOLY]: 30,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 600,
      [AttackPowerType.FROST]: 360,
      [AttackPowerType.POISON]: 1500,
      [AttackPowerType.SCARLET_ROT]: 2000,
    },
    hp: 11000,
    enemyTypes: ["Void"],
  },
  {
    id: "omen",
    name: "Omen",
    defence: {
      [AttackPowerType.PHYSICAL]: 600,
      [AttackPowerType.MAGIC]: 700,
      [AttackPowerType.FIRE]: 700,
      [AttackPowerType.LIGHTNING]: 700,
      [AttackPowerType.HOLY]: 600,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 10,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 20,
      [AttackPowerType.LIGHTNING]: 20,
      [AttackPowerType.HOLY]: -20,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 600,
      [AttackPowerType.FROST]: 360,
      [AttackPowerType.POISON]: 1000,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 3500,
  },
  {
    id: "crucible-knight-npc",
    name: "Crucible Knight",
    defence: {
      [AttackPowerType.PHYSICAL]: 1000,
      [AttackPowerType.MAGIC]: 1000,
      [AttackPowerType.FIRE]: 1000,
      [AttackPowerType.LIGHTNING]: 1000,
      [AttackPowerType.HOLY]: 1000,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 30,
      [AttackPowerType.MAGIC]: 30,
      [AttackPowerType.FIRE]: 30,
      [AttackPowerType.LIGHTNING]: 30,
      [AttackPowerType.HOLY]: 30,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 600,
      [AttackPowerType.FROST]: 480,
      [AttackPowerType.POISON]: 1000,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 6000,
  },
  {
    id: "tree-sentinel-npc",
    name: "Tree Sentinel",
    defence: {
      [AttackPowerType.PHYSICAL]: 1000,
      [AttackPowerType.MAGIC]: 865,
      [AttackPowerType.FIRE]: 700,
      [AttackPowerType.LIGHTNING]: 850,
      [AttackPowerType.HOLY]: 865,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 20,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: -20,
      [AttackPowerType.LIGHTNING]: 30,
      [AttackPowerType.HOLY]: 20,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 600,
      [AttackPowerType.FROST]: 480,
      [AttackPowerType.POISON]: 1000,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 8000,
  },
  {
    id: "bell-bearing-hunter-npc",
    name: "Bell Bearing Hunter",
    defence: {
      [AttackPowerType.PHYSICAL]: 1000,
      [AttackPowerType.MAGIC]: 865,
      [AttackPowerType.FIRE]: 807,
      [AttackPowerType.LIGHTNING]: 765,
      [AttackPowerType.HOLY]: 1004,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 20,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 20,
      [AttackPowerType.LIGHTNING]: 20,
      [AttackPowerType.HOLY]: 40,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 600,
      [AttackPowerType.FROST]: 480,
      [AttackPowerType.POISON]: 1000,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 8500,
  },
  {
    id: "anastasia-tarnished-eater",
    name: "Anastasia Tarnished-Eater",
    defence: {
      [AttackPowerType.PHYSICAL]: 950,
      [AttackPowerType.MAGIC]: 807,
      [AttackPowerType.FIRE]: 807,
      [AttackPowerType.LIGHTNING]: 765,
      [AttackPowerType.HOLY]: 865,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 20,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 30,
      [AttackPowerType.LIGHTNING]: 20,
      [AttackPowerType.HOLY]: 20,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 300,
      [AttackPowerType.FROST]: 360,
      [AttackPowerType.POISON]: 1200,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 7000,
  },
  {
    id: "vargram-the-raging-wolf",
    name: "Vargram the Raging Wolf",
    defence: {
      [AttackPowerType.PHYSICAL]: 1000,
      [AttackPowerType.MAGIC]: 807,
      [AttackPowerType.FIRE]: 807,
      [AttackPowerType.LIGHTNING]: 765,
      [AttackPowerType.HOLY]: 865,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 25,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 20,
      [AttackPowerType.LIGHTNING]: 20,
      [AttackPowerType.HOLY]: 20,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 600,
      [AttackPowerType.FROST]: 480,
      [AttackPowerType.POISON]: 1000,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 7500,
  },
  {
    id: "bernahl",
    name: "Bernahl",
    defence: {
      [AttackPowerType.PHYSICAL]: 1000,
      [AttackPowerType.MAGIC]: 865,
      [AttackPowerType.FIRE]: 807,
      [AttackPowerType.LIGHTNING]: 765,
      [AttackPowerType.HOLY]: 865,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 20,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 20,
      [AttackPowerType.LIGHTNING]: 20,
      [AttackPowerType.HOLY]: 20,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 600,
      [AttackPowerType.FROST]: 480,
      [AttackPowerType.POISON]: 1000,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 8000,
  },
  {
    id: "magma-wyrm-commoner",
    name: "Magma Wyrm (Commoner)",
    defence: {
      [AttackPowerType.PHYSICAL]: 700,
      [AttackPowerType.MAGIC]: 865,
      [AttackPowerType.FIRE]: 1100,
      [AttackPowerType.LIGHTNING]: 765,
      [AttackPowerType.HOLY]: 865,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: -10,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 80,
      [AttackPowerType.LIGHTNING]: 20,
      [AttackPowerType.HOLY]: 20,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 600,
      [AttackPowerType.FROST]: 480,
      [AttackPowerType.POISON]: 1000,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 15000,
    enemyTypes: ["Draconic"],
  },
  {
    id: "adula",
    name: "Adula",
    defence: {
      [AttackPowerType.PHYSICAL]: 1000,
      [AttackPowerType.MAGIC]: 1100,
      [AttackPowerType.FIRE]: 700,
      [AttackPowerType.LIGHTNING]: 765,
      [AttackPowerType.HOLY]: 865,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 20,
      [AttackPowerType.MAGIC]: 40,
      [AttackPowerType.FIRE]: -20,
      [AttackPowerType.LIGHTNING]: 20,
      [AttackPowerType.HOLY]: 20,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 600,
      [AttackPowerType.FROST]: 600,
      [AttackPowerType.POISON]: 1000,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 18000,
    enemyTypes: ["AncientDraconic"],
  },
  {
    id: "commander-niall",
    name: "Commander Niall",
    defence: {
      [AttackPowerType.PHYSICAL]: 1200,
      [AttackPowerType.MAGIC]: 1004,
      [AttackPowerType.FIRE]: 865,
      [AttackPowerType.LIGHTNING]: 1000,
      [AttackPowerType.HOLY]: 1087,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 20,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 30,
      [AttackPowerType.LIGHTNING]: 40,
      [AttackPowerType.HOLY]: 40,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 600,
      [AttackPowerType.FROST]: 480,
      [AttackPowerType.POISON]: 1000,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 14000,
  },
  {
    id: "crucible-knight-ordovis-npc",
    name: "Crucible Knight Ordovis",
    defence: {
      [AttackPowerType.PHYSICAL]: 1100,
      [AttackPowerType.MAGIC]: 1004,
      [AttackPowerType.FIRE]: 1004,
      [AttackPowerType.LIGHTNING]: 1004,
      [AttackPowerType.HOLY]: 1100,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 30,
      [AttackPowerType.MAGIC]: 30,
      [AttackPowerType.FIRE]: 30,
      [AttackPowerType.LIGHTNING]: 30,
      [AttackPowerType.HOLY]: 40,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 600,
      [AttackPowerType.FROST]: 480,
      [AttackPowerType.POISON]: 1000,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 7000,
  },
  {
    id: "elemer-of-the-briar",
    name: "Elemer of the Briar",
    defence: {
      [AttackPowerType.PHYSICAL]: 1100,
      [AttackPowerType.MAGIC]: 1004,
      [AttackPowerType.FIRE]: 865,
      [AttackPowerType.LIGHTNING]: 765,
      [AttackPowerType.HOLY]: 865,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 20,
      [AttackPowerType.MAGIC]: 40,
      [AttackPowerType.FIRE]: 20,
      [AttackPowerType.LIGHTNING]: 20,
      [AttackPowerType.HOLY]: 20,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 600,
      [AttackPowerType.FROST]: 480,
      [AttackPowerType.POISON]: 1000,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 9000,
  },
  {
    id: "royal-knight-loretta",
    name: "Royal Knight Loretta",
    defence: {
      [AttackPowerType.PHYSICAL]: 1000,
      [AttackPowerType.MAGIC]: 1087,
      [AttackPowerType.FIRE]: 865,
      [AttackPowerType.LIGHTNING]: 765,
      [AttackPowerType.HOLY]: 865,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: -10,
      [AttackPowerType.MAGIC]: 40,
      [AttackPowerType.FIRE]: 20,
      [AttackPowerType.LIGHTNING]: 20,
      [AttackPowerType.HOLY]: 20,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 600,
      [AttackPowerType.FROST]: 600,
      [AttackPowerType.POISON]: 1000,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 12000,
  },
  {
    id: "rellana-twin-moon-knight",
    name: "Rellana, Twin Moon Knight",
    defence: {
      [AttackPowerType.PHYSICAL]: 1300,
      [AttackPowerType.MAGIC]: 1100,
      [AttackPowerType.FIRE]: 865,
      [AttackPowerType.LIGHTNING]: 765,
      [AttackPowerType.HOLY]: 1100,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 20,
      [AttackPowerType.MAGIC]: 40,
      [AttackPowerType.FIRE]: 20,
      [AttackPowerType.LIGHTNING]: 20,
      [AttackPowerType.HOLY]: 40,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 600,
      [AttackPowerType.FROST]: 480,
      [AttackPowerType.POISON]: 1000,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 22000,
  },
  {
    id: "dancing-lion",
    name: "Dancing Lion",
    defence: {
      [AttackPowerType.PHYSICAL]: 1200,
      [AttackPowerType.MAGIC]: 1004,
      [AttackPowerType.FIRE]: 865,
      [AttackPowerType.LIGHTNING]: 900,
      [AttackPowerType.HOLY]: 865,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 20,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 40,
      [AttackPowerType.LIGHTNING]: 40,
      [AttackPowerType.HOLY]: 20,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 600,
      [AttackPowerType.FROST]: 600,
      [AttackPowerType.POISON]: 1000,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 18000,
  },
  {
    id: "scadutree-avatar",
    name: "Scadutree Avatar",
    defence: {
      [AttackPowerType.PHYSICAL]: 1200,
      [AttackPowerType.MAGIC]: 865,
      [AttackPowerType.FIRE]: 807,
      [AttackPowerType.LIGHTNING]: 765,
      [AttackPowerType.HOLY]: 1100,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 20,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 20,
      [AttackPowerType.LIGHTNING]: 20,
      [AttackPowerType.HOLY]: 40,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 600,
      [AttackPowerType.FROST]: 480,
      [AttackPowerType.POISON]: 1500,
      [AttackPowerType.SCARLET_ROT]: 2000,
    },
    hp: 16000,
  },

  // ─── v1.1.0 enemy expansion ──────────────────────────────────────────────
  // Values sourced from community data (NpcParam / CalcCorrectGraph).
  // Some entries use approximated values where exact datamined values were
  // unavailable — noted inline.

  {
    // Gideon Ofnir — All-Knowing, final Leyndell boss before Radagon.
    // Magic-focused caster with moderate defences. Approximate values.
    id: "gideon-ofnir",
    name: "Sir Gideon Ofnir, All-Knowing",
    defence: {
      [AttackPowerType.PHYSICAL]: 1100,
      [AttackPowerType.MAGIC]: 1087,
      [AttackPowerType.FIRE]: 807,
      [AttackPowerType.LIGHTNING]: 765,
      [AttackPowerType.HOLY]: 924,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 10,
      [AttackPowerType.MAGIC]: 40,
      [AttackPowerType.FIRE]: 30,
      [AttackPowerType.LIGHTNING]: 30,
      [AttackPowerType.HOLY]: 30,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 600,
      [AttackPowerType.FROST]: 600,
      [AttackPowerType.POISON]: 1000,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 15000,
    enemyTypes: ["Demigod"],
  },
  {
    // Hoarah Loux — warrior form of Godfrey (phase 2 of the boss fight).
    // Bare-handed martial artist. High physical defence, no heavy armour.
    id: "hoarah-loux-warrior",
    name: "Hoarah Loux, Warrior",
    defence: {
      [AttackPowerType.PHYSICAL]: 1200,
      [AttackPowerType.MAGIC]: 1087,
      [AttackPowerType.FIRE]: 865,
      [AttackPowerType.LIGHTNING]: 765,
      [AttackPowerType.HOLY]: 807,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 10,
      [AttackPowerType.MAGIC]: 30,
      [AttackPowerType.FIRE]: 30,
      [AttackPowerType.LIGHTNING]: 30,
      [AttackPowerType.HOLY]: 30,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 600,
      [AttackPowerType.FROST]: 600,
      [AttackPowerType.POISON]: 1000,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 37395,
    enemyTypes: ["Void", "Demigod"],
  },
  {
    // Lichdragon Fortissax — secret dragon boss in Deeproot Depths.
    // HIGH holy weakness, lightning resistance. Living in death.
    id: "lichdragon-fortissax",
    name: "Lichdragon Fortissax",
    defence: {
      [AttackPowerType.PHYSICAL]: 1273,
      [AttackPowerType.MAGIC]: 1088,
      [AttackPowerType.FIRE]: 1168,
      [AttackPowerType.LIGHTNING]: 1004,
      [AttackPowerType.HOLY]: 904,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 20,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 40,
      [AttackPowerType.LIGHTNING]: 10,
      [AttackPowerType.HOLY]: -10,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 760,
      [AttackPowerType.FROST]: 600,
      [AttackPowerType.POISON]: 1000,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 39000,
    enemyTypes: ["Draconic", "LivingInDeath"],
  },
  {
    // Fallingstar Beast (full boss version) — this is the more complete
    // boss in Sellia / GT region variant with higher HP than the common one.
    id: "fallingstar-beast-boss",
    name: "Fallingstar Beast (Boss)",
    defence: {
      [AttackPowerType.PHYSICAL]: 1200,
      [AttackPowerType.MAGIC]: 865,
      [AttackPowerType.FIRE]: 1181,
      [AttackPowerType.LIGHTNING]: 765,
      [AttackPowerType.HOLY]: 1087,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 20,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 40,
      [AttackPowerType.LIGHTNING]: 10,
      [AttackPowerType.HOLY]: 20,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 600,
      [AttackPowerType.FROST]: 600,
      [AttackPowerType.POISON]: 1000,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 12700,
    enemyTypes: ["Alien"],
  },
  {
    // Black Knife Assassin (Alecto boss version) — the field boss in
    // Consecrated Snowfield. Higher HP than the common dungeon assassin.
    id: "black-knife-assassin-alecto",
    name: "Black Knife Assassin (Alecto)",
    defence: {
      [AttackPowerType.PHYSICAL]: 1000,
      [AttackPowerType.MAGIC]: 865,
      [AttackPowerType.FIRE]: 807,
      [AttackPowerType.LIGHTNING]: 765,
      [AttackPowerType.HOLY]: 924,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 10,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 20,
      [AttackPowerType.LIGHTNING]: 20,
      [AttackPowerType.HOLY]: 40,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 420,
      [AttackPowerType.FROST]: 360,
      [AttackPowerType.POISON]: 900,
      [AttackPowerType.SCARLET_ROT]: 1200,
    },
    hp: 6500,
    enemyTypes: ["Knight", "LivingInDeath"],
  },
  {
    // Tree Sentinel duo — the pair guarding the capital approach.
    // Combined HP of two sentinels. Approximate values.
    id: "tree-sentinel-duo",
    name: "Tree Sentinel Duo",
    defence: {
      [AttackPowerType.PHYSICAL]: 1100,
      [AttackPowerType.MAGIC]: 865,
      [AttackPowerType.FIRE]: 807,
      [AttackPowerType.LIGHTNING]: 807,
      [AttackPowerType.HOLY]: 807,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 20,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 20,
      [AttackPowerType.LIGHTNING]: 0,
      [AttackPowerType.HOLY]: 20,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 480,
      [AttackPowerType.FROST]: 600,
      [AttackPowerType.POISON]: 1000,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 9400,
    enemyTypes: ["Knight"],
  },
  {
    // Crucible Knight duo — two Crucible Knights (Ordovis + Siluria variant)
    // fought together at Stormveil / Erdtree-Gazing Hill. Approximate values.
    id: "crucible-knight-duo",
    name: "Crucible Knight Duo",
    defence: {
      [AttackPowerType.PHYSICAL]: 1100,
      [AttackPowerType.MAGIC]: 865,
      [AttackPowerType.FIRE]: 807,
      [AttackPowerType.LIGHTNING]: 765,
      [AttackPowerType.HOLY]: 865,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 30,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 20,
      [AttackPowerType.LIGHTNING]: 20,
      [AttackPowerType.HOLY]: 20,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 300,
      [AttackPowerType.FROST]: 300,
      [AttackPowerType.POISON]: 900,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 12000,
    enemyTypes: ["Knight"],
  },
  {
    // Bell-bearing Hunter (Nighttime field boss in Altus / Caelid / etc.)
    // Approximate values from similar NPC-type enemies.
    id: "bell-bearing-hunter-night",
    name: "Bell-Bearing Hunter (Night)",
    defence: {
      [AttackPowerType.PHYSICAL]: 1100,
      [AttackPowerType.MAGIC]: 924,
      [AttackPowerType.FIRE]: 865,
      [AttackPowerType.LIGHTNING]: 765,
      [AttackPowerType.HOLY]: 865,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 20,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 20,
      [AttackPowerType.LIGHTNING]: 10,
      [AttackPowerType.HOLY]: 20,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 300,
      [AttackPowerType.FROST]: 300,
      [AttackPowerType.POISON]: 900,
      [AttackPowerType.SCARLET_ROT]: 1200,
    },
    hp: 5500,
  },
  {
    // Millicent — NPC invader encountered during her questline.
    // Uses Waterfowl-style dagger moves. Approximate values.
    id: "millicent-npc",
    name: "Millicent (NPC)",
    defence: {
      [AttackPowerType.PHYSICAL]: 900,
      [AttackPowerType.MAGIC]: 807,
      [AttackPowerType.FIRE]: 807,
      [AttackPowerType.LIGHTNING]: 765,
      [AttackPowerType.HOLY]: 865,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 10,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 20,
      [AttackPowerType.LIGHTNING]: 20,
      [AttackPowerType.HOLY]: 20,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 1200,
      [AttackPowerType.FROST]: 480,
      [AttackPowerType.POISON]: 900,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 6000,
  },
  {
    // Bloody Finger Hunter Yura — NPC fought in his invasion encounter.
    // Approximate values based on similar NPC invaders.
    id: "bloody-finger-hunter-yura",
    name: "Bloody Finger Hunter Yura",
    defence: {
      [AttackPowerType.PHYSICAL]: 950,
      [AttackPowerType.MAGIC]: 807,
      [AttackPowerType.FIRE]: 807,
      [AttackPowerType.LIGHTNING]: 765,
      [AttackPowerType.HOLY]: 865,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 15,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 20,
      [AttackPowerType.LIGHTNING]: 20,
      [AttackPowerType.HOLY]: 20,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 600,
      [AttackPowerType.FROST]: 600,
      [AttackPowerType.POISON]: 900,
      [AttackPowerType.SCARLET_ROT]: 1500,
    },
    hp: 5500,
    enemyTypes: ["Knight"],
  },
  {
    // Generic Knight — baseline comparison enemy representing a common
    // Leyndell / Haligtree knight. Approximate average values.
    id: "generic-knight",
    name: "Generic Knight",
    defence: {
      [AttackPowerType.PHYSICAL]: 1000,
      [AttackPowerType.MAGIC]: 807,
      [AttackPowerType.FIRE]: 807,
      [AttackPowerType.LIGHTNING]: 765,
      [AttackPowerType.HOLY]: 865,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 20,
      [AttackPowerType.MAGIC]: 20,
      [AttackPowerType.FIRE]: 20,
      [AttackPowerType.LIGHTNING]: 10,
      [AttackPowerType.HOLY]: 30,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 480,
      [AttackPowerType.FROST]: 480,
      [AttackPowerType.POISON]: 900,
      [AttackPowerType.SCARLET_ROT]: 1200,
    },
    hp: 4000,
    enemyTypes: ["Knight"],
  },
  {
    // Generic Soldier — baseline comparison enemy representing a common
    // godrick / leyndell foot soldier. Low across the board.
    id: "generic-soldier",
    name: "Generic Soldier",
    defence: {
      [AttackPowerType.PHYSICAL]: 600,
      [AttackPowerType.MAGIC]: 700,
      [AttackPowerType.FIRE]: 700,
      [AttackPowerType.LIGHTNING]: 700,
      [AttackPowerType.HOLY]: 800,
    },
    absorption: {
      [AttackPowerType.PHYSICAL]: 10,
      [AttackPowerType.MAGIC]: 10,
      [AttackPowerType.FIRE]: 10,
      [AttackPowerType.LIGHTNING]: 10,
      [AttackPowerType.HOLY]: 10,
    },
    statusResistances: {
      [AttackPowerType.BLEED]: 360,
      [AttackPowerType.FROST]: 360,
      [AttackPowerType.POISON]: 780,
      [AttackPowerType.SCARLET_ROT]: 1000,
    },
    hp: 2500,
  },
];
